In [3]:
import numpy as np

#df = np.random.randint(0,100,(10,5))

In [4]:
#[Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_active]

banking_data = np.array([
    [1, 100000, 720, 15, 2],
    [2, 150000, 650, 42, 8],
    [3, 300000, 500, 5, 1],
    [4, 870000, 810, 30, 6],
    [5, 430000, 690, 18, 3],
    [6, 120000, 745, 55, 10],
    [7, 760000, 600, 8, 1],
    [8, 220000, 860, 70, 12],
    [9, 900000, 700, 17, 5],
    [10, 670000, 675, 22, 4]
])

print(banking_data)

[[     1 100000    720     15      2]
 [     2 150000    650     42      8]
 [     3 300000    500      5      1]
 [     4 870000    810     30      6]
 [     5 430000    690     18      3]
 [     6 120000    745     55     10]
 [     7 760000    600      8      1]
 [     8 220000    860     70     12]
 [     9 900000    700     17      5]
 [    10 670000    675     22      4]]


In [ ]:
# Q1.1: Create a 4x4 identity matrix using np.eye()
identity_matrix = np.eye(4,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Q1.2: Create an array of 8 zeros using np.zeros()

Array_with_zeros = np.zeros(8)
Array_with_zeros

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Create an array of 6 ones using np.ones()
ones = np.ones(6)
ones

array([1., 1., 1., 1., 1., 1.])

In [ ]:
#Create an array with values from 0 to 15 using np.arange()

demo = np.arange(0,15)
demo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

data = np.linspace(0,100,8)
data

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

# Question 2: Array Attributes and Information



In [ ]:
# Q2.1: What is the shape of the banking_data array?
print(np.shape(banking_data))

(10, 5)


In [ ]:
# Q2.2: What is the data type of the banking_data array?
print(type(banking_data))

<class 'numpy.ndarray'>


In [ ]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
print(np.size(banking_data))


50


In [ ]:
#Q2.4: What is the number of dimensions of the banking_data array?



In [ ]:
# Q2.5: What is the memory size of the banking_data array in bytes?



# Question 3: Indexing and Slicing

In [ ]:
 #Q3.1: Extract the first row of banking_data

#Q3.2: Extract the last row of banking_data

#Q3.3: Extract the Account_Balance column (column index 1)

#Q3.4: Extract the first 4 rows and first 3 columns

#Q3.5: Extract rows 3 to 7 (inclusive)

In [ ]:
banking_data

array([[     1, 100000,    720,     15,      2],
       [     2, 150000,    650,     42,      8],
       [     3, 300000,    500,      5,      1],
       [     4, 870000,    810,     30,      6],
       [     5, 430000,    690,     18,      3],
       [     6, 120000,    745,     55,     10],
       [     7, 760000,    600,      8,      1],
       [     8, 220000,    860,     70,     12],
       [     9, 900000,    700,     17,      5],
       [    10, 670000,    675,     22,      4]])

In [ ]:
# first row
print(banking_data[:1])

[[     1 100000    720     15      2]]


In [ ]:
#last row
banking_data[-1]

array([    10, 670000,    675,     22,      4])

In [ ]:



 # Extract the Account_Balance column (column index 1)
print(banking_data[:,1:2])

[[100000]
 [150000]
 [300000]
 [870000]
 [430000]
 [120000]
 [760000]
 [220000]
 [900000]
 [670000]]


In [ ]:
#Q3.4: Extract the first 4 rows and first 3 columns

print(banking_data[0:4,0:3])

[[     1 100000    720]
 [     2 150000    650]
 [     3 300000    500]
 [     4 870000    810]]


In [ ]:
#Q3.5: Extract rows 3 to 7 (inclusive)

banking_data[2:7,:]

array([[     3, 300000,    500,      5,      1],
       [     4, 870000,    810,     30,      6],
       [     5, 430000,    690,     18,      3],
       [     6, 120000,    745,     55,     10],
       [     7, 760000,    600,      8,      1]])

# Question 4: Mathematical Operations

In [ ]:
#Q4.1: Calculate the sum of all account balances

#Q4.2: Calculate the mean account balance

#Q4.3: Calculate the standard deviation of account balances

#Q4.4: Calculate the variance of account balances

#Q4.5: Calculate the median account balance

In [ ]:
# sum account balances
print(banking_data)

print("Sum :-",banking_data[:,1:2].sum())


[[     1 100000    720     15      2]
 [     2 150000    650     42      8]
 [     3 300000    500      5      1]
 [     4 870000    810     30      6]
 [     5 430000    690     18      3]
 [     6 120000    745     55     10]
 [     7 760000    600      8      1]
 [     8 220000    860     70     12]
 [     9 900000    700     17      5]
 [    10 670000    675     22      4]]
Sum :- 4520000


In [ ]:
#Q4.2: Calculate the mean account balance
print("Mean :-",banking_data[:,1:2].mean())


Mean :- 452000.0


In [ ]:
#Q4.3: Calculate the standard deviation of account balances
print("SD :-",banking_data[:,1:2].std())

SD :- 303407.3169849402


In [ ]:
#Q4.4: Calculate the variance of account balances
print("variance :-",banking_data[:,1:2].var())


variance :- 92056000000.0


In [ ]:
#Q4.5: Calculate the median account balance
m=banking_data[:,1:2]
np.median(m)


np.float64(365000.0)

# Question 5: Statistical Functions

In [ ]:
#Q5.1: Find the minimum and maximum account balances

#Q5.2: Find the minimum and maximum credit scores

#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)

#Q5.4: Calculate the correlation between account balance and credit score

#Q5.5: Calculate the covariance between account balance and credit score

In [ ]:
print(banking_data[:,1:2])

[[100000]
 [150000]
 [300000]
 [870000]
 [430000]
 [120000]
 [760000]
 [220000]
 [900000]
 [670000]]


In [ ]:
# min max account balances
print("min:-",banking_data[:,1:2].min())

print("max:-",banking_data[:,1:2].max())

min:- 100000
max:- 900000


In [ ]:
#Q5.2: Find the minimum and maximum credit scores
print(banking_data[:,2:3].min())
print(banking_data[:,2:3].max())

500
860


In [ ]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)




In [ ]:
#Q5.4: Calculate the correlation between account balance and credit score
np.corrcoef(banking_data[:,1:3])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#Q5.5: Calculate the covariance between account balance and credit score
np.cov(banking_data[:,1:3])

array([[4.92825920e+09, 7.41373400e+09, 1.48671800e+10, 4.31465916e+10,
        2.13109484e+10, 5.91981820e+09, 3.76966160e+10, 1.08781096e+10,
        4.46412520e+10, 3.32252930e+10],
       [7.41373400e+09, 1.11527112e+10, 2.23651625e+10, 6.49067632e+10,
        3.20587242e+10, 8.90536712e+09, 5.67081950e+10, 1.63642795e+10,
        6.71552275e+10, 4.99818444e+10],
       [1.48671800e+10, 2.23651625e+10, 4.48501250e+10, 1.30161202e+11,
        6.42891725e+10, 1.78584362e+10, 1.13720150e+11, 3.28162150e+10,
        1.34670175e+11, 1.00231419e+11],
       [4.31465916e+10, 6.49067632e+10, 1.30161202e+11, 3.77745628e+11,
        1.86575979e+11, 5.18276267e+10, 3.30031443e+11, 9.52371483e+10,
        3.90831284e+11, 2.90885298e+11],
       [2.13109484e+10, 3.20587242e+10, 6.42891725e+10, 1.86575979e+11,
        9.21535380e+10, 2.55986820e+10, 1.63009007e+11, 4.70394967e+10,
        1.93039242e+11, 1.43673958e+11],
       [5.91981820e+09, 8.90536712e+09, 1.78584362e+10, 5.18276267e+10,
   

#Array Reshaping and Manipulation

In [ ]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns

# Q6.2: Flatten the banking_data to a 1D array

# Q6.3: Transpose the banking_data

# Q6.4: Split the banking_data into 2 equal parts vertically

# Q6.5: Split the banking_data into 2 equal parts horizontally

In [ ]:
banking_data

array([[     1, 100000,    720,     15,      2],
       [     2, 150000,    650,     42,      8],
       [     3, 300000,    500,      5,      1],
       [     4, 870000,    810,     30,      6],
       [     5, 430000,    690,     18,      3],
       [     6, 120000,    745,     55,     10],
       [     7, 760000,    600,      8,      1],
       [     8, 220000,    860,     70,     12],
       [     9, 900000,    700,     17,      5],
       [    10, 670000,    675,     22,      4]])

In [ ]:
# Reshape the banking_data to 5 rows × 10 columns
print(banking_data.reshape(5,10))

[[     1 100000    720     15      2      2 150000    650     42      8]
 [     3 300000    500      5      1      4 870000    810     30      6]
 [     5 430000    690     18      3      6 120000    745     55     10]
 [     7 760000    600      8      1      8 220000    860     70     12]
 [     9 900000    700     17      5     10 670000    675     22      4]]


In [ ]:
# 1D array
print(banking_data.ravel())

[     1 100000    720     15      2      2 150000    650     42      8
      3 300000    500      5      1      4 870000    810     30      6
      5 430000    690     18      3      6 120000    745     55     10
      7 760000    600      8      1      8 220000    860     70     12
      9 900000    700     17      5     10 670000    675     22      4]


In [ ]:
# Q6.3: Transpose the banking_data
print(banking_data.T)

[[     1      2      3      4      5      6      7      8      9     10]
 [100000 150000 300000 870000 430000 120000 760000 220000 900000 670000]
 [   720    650    500    810    690    745    600    860    700    675]
 [    15     42      5     30     18     55      8     70     17     22]
 [     2      8      1      6      3     10      1     12      5      4]]


In [6]:
# Q6.4: Split the banking_data into 2 equal parts vertically
print(banking_data)
np.vsplit(banking_data,2)

[[     1 100000    720     15      2]
 [     2 150000    650     42      8]
 [     3 300000    500      5      1]
 [     4 870000    810     30      6]
 [     5 430000    690     18      3]
 [     6 120000    745     55     10]
 [     7 760000    600      8      1]
 [     8 220000    860     70     12]
 [     9 900000    700     17      5]
 [    10 670000    675     22      4]]


[array([[     1, 100000,    720,     15,      2],
        [     2, 150000,    650,     42,      8],
        [     3, 300000,    500,      5,      1],
        [     4, 870000,    810,     30,      6],
        [     5, 430000,    690,     18,      3]]),
 array([[     6, 120000,    745,     55,     10],
        [     7, 760000,    600,      8,      1],
        [     8, 220000,    860,     70,     12],
        [     9, 900000,    700,     17,      5],
        [    10, 670000,    675,     22,      4]])]

In [8]:
# Q6.5: Split the banking_data into 2 equal parts horizontally

np.hsplit(banking_data,[2])

[array([[     1, 100000],
        [     2, 150000],
        [     3, 300000],
        [     4, 870000],
        [     5, 430000],
        [     6, 120000],
        [     7, 760000],
        [     8, 220000],
        [     9, 900000],
        [    10, 670000]]),
 array([[720,  15,   2],
        [650,  42,   8],
        [500,   5,   1],
        [810,  30,   6],
        [690,  18,   3],
        [745,  55,  10],
        [600,   8,   1],
        [860,  70,  12],
        [700,  17,   5],
        [675,  22,   4]])]

# Question 7: Logical Operations and Filtering
# Q7.1: Find customers with account balance greater than $100,000

# Q7.2: Find customers with credit score greater than 800
# #
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750

# Q7.4: Count how many customers have account balance between $10,000 and $100,000

# Q7.5: Find the index of the customer with the highest credit score

In [21]:
#Q7.1: Find customers with account balance greater than $100,000
x =banking_data[banking_data[:,1]>100000]
print(x)

[[     2 150000    650     42      8]
 [     3 300000    500      5      1]
 [     4 870000    810     30      6]
 [     5 430000    690     18      3]
 [     6 120000    745     55     10]
 [     7 760000    600      8      1]
 [     8 220000    860     70     12]
 [     9 900000    700     17      5]
 [    10 670000    675     22      4]]


In [22]:
# Q7.2: Find customers with credit score greater than 800
y =banking_data[banking_data[:,2]>800]
print(y)


[[     4 870000    810     30      6]
 [     8 220000    860     70     12]]


In [25]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
y =banking_data[(banking_data[:,3]>50) & (banking_data[:,2]<750)]
print(y)
# Q7.4: Count how many customers have account balance between $10,000 and $100,000

# Q7.5: Find the index of the customer with the highest credit score

[[     6 120000    745     55     10]]


In [34]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
y=banking_data[(banking_data[:,1]>10000) & (banking_data[:,1]<100000)]
print(y)


[]


In [39]:
# Q7.5: Find the index of the customer with the highest credit score
print(banking_data[:,2].argmax()+1)

# to verify whole data
print(banking_data)

8
[[     1 100000    720     15      2]
 [     2 150000    650     42      8]
 [     3 300000    500      5      1]
 [     4 870000    810     30      6]
 [     5 430000    690     18      3]
 [     6 120000    745     55     10]
 [     7 760000    600      8      1]
 [     8 220000    860     70     12]
 [     9 900000    700     17      5]
 [    10 670000    675     22      4]]


In [ ]:
# Question 8: Sorting and Searching
# Q8.1: Sort the banking_data by account balance (ascending)

# Q8.2: Sort the banking_data by credit score (descending)

# Q8.3: Find the indices that would sort the array by years active

# Q8.4: Find the customer with the second highest account balance

# Q8.5: Find the customer with the lowest transaction count

In [40]:
sorted_by_balance = banking_data[banking_data[:, 1].argsort()]
print(sorted_by_balance)


[[     1 100000    720     15      2]
 [     6 120000    745     55     10]
 [     2 150000    650     42      8]
 [     8 220000    860     70     12]
 [     3 300000    500      5      1]
 [     5 430000    690     18      3]
 [    10 670000    675     22      4]
 [     7 760000    600      8      1]
 [     4 870000    810     30      6]
 [     9 900000    700     17      5]]


In [41]:
sorted_by_credit = banking_data[(-banking_data[:, 2]).argsort()]
print(sorted_by_credit)


[[     8 220000    860     70     12]
 [     4 870000    810     30      6]
 [     6 120000    745     55     10]
 [     1 100000    720     15      2]
 [     9 900000    700     17      5]
 [     5 430000    690     18      3]
 [    10 670000    675     22      4]
 [     2 150000    650     42      8]
 [     7 760000    600      8      1]
 [     3 300000    500      5      1]]


In [42]:
indices_yearsactive = banking_data[:, 4].argsort()
print(indices_yearsactive)


[2 6 0 4 9 8 3 1 5 7]


In [43]:
sorted_balance_desc = banking_data[(-banking_data[:, 1]).argsort()]
second_highest = sorted_balance_desc[1]
print(second_highest)


[     4 870000    810     30      6]


In [44]:
min_tranx_index = banking_data[:, 3].argmin()
customer_lowest_tranx = banking_data[min_tranx_index]
print(customer_lowest_tranx)


[     3 300000    500      5      1]
