In [1]:
import numpy as np
data = np.random.randint(0,10,10)
data

array([6, 1, 8, 7, 9, 8, 7, 0, 3, 3])

In [ ]:
data>5

array([ True, False,  True, False,  True, False, False, False,  True,
        True])

In [ ]:
data[data>5]

array([6, 9, 6, 7, 9])

In [ ]:
#2. > 50 and <50
data = np.random.randint(0,100,10)
print(data)
print(data[data>50])
print(data[data<50])

[87 58 64 34 31 15 34 10 35 39]
[87 58 64]
[34 31 15 34 10 35 39]


In [ ]:
# for  greater than average
data[data>data.mean()]

array([87, 58, 64])

In [ ]:
np.mean(data)

np.float64(40.7)

In [ ]:
#Array Manipulation
data1 = np.random.randint(0,100,(5,5))
data1

array([[22, 47, 90, 89, 42],
       [71, 12,  9, 13, 70],
       [53, 79, 50, 65, 69],
       [ 7, 27, 24,  5,  8],
       [34, 15, 58, 88, 43]])

In [ ]:
#  ravel makes into straight format
data1.ravel()

array([22, 47, 90, 89, 42, 71, 12,  9, 13, 70, 53, 79, 50, 65, 69,  7, 27,
       24,  5,  8, 34, 15, 58, 88, 43])

In [ ]:
data1.T  #transpose converted rows to the columns

array([[22, 71, 53,  7, 34],
       [47, 12, 79, 27, 15],
       [90,  9, 50, 24, 58],
       [89, 13, 65,  5, 88],
       [42, 70, 69,  8, 43]])

In [ ]:
data2=np.random.randint(0,100,(5,5))
data2

array([[75, 54, 44, 93, 35],
       [ 0, 66, 48, 82, 18],
       [37,  9, 54, 57,  4],
       [82, 84, 63, 77, 45],
       [12, 67, 24, 14, 17]])

In [ ]:
np.hstack([data1,data2]) # stack beside data1 in horzontal similarly we have np.vstack([data1,data2])

array([[22, 47, 90, 89, 42, 75, 54, 44, 93, 35],
       [71, 12,  9, 13, 70,  0, 66, 48, 82, 18],
       [53, 79, 50, 65, 69, 37,  9, 54, 57,  4],
       [ 7, 27, 24,  5,  8, 82, 84, 63, 77, 45],
       [34, 15, 58, 88, 43, 12, 67, 24, 14, 17]])

In [ ]:
np.vstack([data1,data2])

array([[22, 47, 90, 89, 42],
       [71, 12,  9, 13, 70],
       [53, 79, 50, 65, 69],
       [ 7, 27, 24,  5,  8],
       [34, 15, 58, 88, 43],
       [75, 54, 44, 93, 35],
       [ 0, 66, 48, 82, 18],
       [37,  9, 54, 57,  4],
       [82, 84, 63, 77, 45],
       [12, 67, 24, 14, 17]])

###  NUMPY IMP CONCEPTS


# **Correlation x and Y and Z**


In [ ]:
m = np.random.randint(0,10,(3,4))
m

array([[5, 1, 5, 7],
       [9, 4, 3, 9],
       [5, 2, 9, 7]])

In [ ]:
m.T

array([[5, 9, 5],
       [1, 4, 2],
       [5, 3, 9],
       [7, 9, 7]])

In [ ]:
# it calculates correlation of first column and 2nd column and 3rd column
np.corrcoef(m)

array([[ 1.        ,  0.59988588,  0.77624596],
       [ 0.59988588,  1.        , -0.02615031],
       [ 0.77624596, -0.02615031,  1.        ]])

In [ ]:
# np.loadtxt(" path ",delimeter=',',skiprows=1)

In [2]:
data = np.random.randint(0,100,(10,10))
data


array([[34, 60, 94, 32, 48, 74, 60, 50,  7, 55],
       [98, 31, 48, 81, 27, 33,  5, 11, 34, 40],
       [40, 39, 50, 26, 56, 69, 28, 67, 71, 48],
       [77, 67, 24, 47,  1, 31, 98, 95, 14, 84],
       [94, 36, 30, 90,  7,  6, 59, 73, 92, 52],
       [43, 33, 91, 86, 46, 98, 71, 99, 18, 30],
       [24, 48, 99, 96, 35, 21, 36, 90, 10, 44],
       [31, 45, 57, 76, 65, 39, 10, 16, 32, 48],
       [10, 96, 59, 21, 22, 60, 83, 54, 59, 38],
       [12,  8, 20, 24, 30, 17, 84, 51, 16, 58]])

In [3]:
np.save("random.txt",data)

In [4]:
np.load("/content/random.txt.npy")

array([[34, 60, 94, 32, 48, 74, 60, 50,  7, 55],
       [98, 31, 48, 81, 27, 33,  5, 11, 34, 40],
       [40, 39, 50, 26, 56, 69, 28, 67, 71, 48],
       [77, 67, 24, 47,  1, 31, 98, 95, 14, 84],
       [94, 36, 30, 90,  7,  6, 59, 73, 92, 52],
       [43, 33, 91, 86, 46, 98, 71, 99, 18, 30],
       [24, 48, 99, 96, 35, 21, 36, 90, 10, 44],
       [31, 45, 57, 76, 65, 39, 10, 16, 32, 48],
       [10, 96, 59, 21, 22, 60, 83, 54, 59, 38],
       [12,  8, 20, 24, 30, 17, 84, 51, 16, 58]])

In [17]:
import numpy as np
a =open('/content/sample.txt')
print(a.read())

hello this is a sample text 
hello this is a sample text 
hello this is a sample text 
hello this is a sample text v
hello this is a sample text 

hello this is a sample text 
