In [ ]:
import numpy as np
data = np.random.randint(0,10,(5,5))
data

array([[7, 4, 0, 0, 4],
       [5, 5, 8, 5, 1],
       [3, 5, 3, 3, 6],
       [5, 5, 4, 4, 7],
       [6, 7, 4, 1, 9]])

In [ ]:
data[-2:-1,-2:-1]

array([[4]])

In [ ]:
x=[1,2,3,4,5]
y=np.array([1,2,3,4,5,5,])
print(type(x))
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#list cannot perform x/2 whereas numpy array can
y/2


array([0.5, 1. , 1.5, 2. , 2.5, 2.5])

In [ ]:
z=np.array([2.45,3,4,5,5,])
print(z)
#here one element is float so it convertes all element into float and even same with string

l=np.array([2.45,3,4,5,5,"data","car"])
print(l) #all r string

[2.45 3.   4.   5.   5.  ]
['2.45' '3' '4' '5' '5' 'data' 'car']


In [ ]:
m=np.array([4,5,5,3])
m*5


array([20, 25, 25, 15])

In [ ]:
#generate random numbers
np.random.randint(0,100,5)
np.random.randint(0,100,(4,4))

array([[43, 85,  5, 77],
       [40, 99, 24, 72],
       [63, 11, 14, 16],
       [67,  5, 88, 21]])

In [ ]:
np.random.rand(10)

array([0.65704764, 0.93459886, 0.66205619, 0.61894274, 0.27261734,
       0.85785795, 0.74662416, 0.76481553, 0.03704579, 0.83194753])

In [ ]:
# normalization
d= np.array([1,2,3,4])
(d-d.min())/(d.max()-d.min())


array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
#mean median mode standard Deviation, variance, range
m= np.random.randint(0,100,10)
print(m)

[26  9 10 73 71 70 22 24 43 50]


In [ ]:
print(np.mean(m))
print(np.median(m))

39.8
34.5


In [ ]:
np.std(m)
np.var(m)


np.float64(569.56)

In [ ]:
#Axis
import numpy as np
n= np.random.randint(0,5,(3,3))
print(n)

[[1 4 0]
 [2 4 4]
 [3 0 0]]


In [ ]:
print(n.sum(axis=1))  #row no is added
print(n.sum(axis=0))  #column no is added

[ 5 10  3]
[6 8 4]


In [ ]:
n= np.random.randint(0,10,10)
print(n)
print(n.min())
n.argmin()  # prints index of min value

[4 2 4 5 1 9 7 7 2 9]
1


np.int64(4)

In [ ]:
n= np.random.randint(0,10,(5,5))
print(n)
# Add only second column and print 0+5+1+3+3

[[0 0 2 4 4]
 [3 5 9 3 4]
 [3 1 2 8 0]
 [7 3 3 5 9]
 [0 3 8 7 0]]


np.int64(5)

In [ ]:
n[:,1].sum()

np.int64(12)

In [ ]:
#max of 4th cloumn index print
n[:,-2].argmax()

np.int64(2)

In [ ]:
# numpy broadcasting is nothing but it makes an copy if there is no matching size of both array
data= np.array([2,4,5,6])
m= 10  #creates copy like ([10,10,10,10]) to match the size
data+10

array([12, 14, 15, 16])